# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(813, 656)
        App.setAutoFillBackground(False)
        App.setStyleSheet("QMainWindow {\n"
"    background-color: #ffff66;\n"
"    border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(App)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 20, 321, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pokupka = QtWidgets.QPushButton(self.centralwidget)
        self.pokupka.setGeometry(QtCore.QRect(30, 290, 191, 51))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.pokupka.setFont(font)
        self.pokupka.setStyleSheet("QPushButton { background-color: #20AA4C;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.pokupka.setObjectName("pokupka")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(490, 70, 312, 183))
        self.calendarWidget.setStyleSheet("QCalendarWidget { border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;}")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 211, 71))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.prodaja = QtWidgets.QPushButton(self.centralwidget)
        self.prodaja.setGeometry(QtCore.QRect(30, 360, 191, 51))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.prodaja.setFont(font)
        self.prodaja.setStyleSheet("QPushButton { background-color: #AA2F20;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.prodaja.setObjectName("prodaja")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.vivod = QtWidgets.QTextBrowser(self.centralwidget)
        self.vivod.setGeometry(QtCore.QRect(245, 291, 541, 311))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.vivod.setFont(font)
        self.vivod.setStyleSheet("QTextBrowser { border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;}")
        self.vivod.setObjectName("vivod")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(250, 70, 51, 31))
        self.spinBox.setObjectName("spinBox")
        self.infa = QtWidgets.QPushButton(self.centralwidget)
        self.infa.setGeometry(QtCore.QRect(30, 430, 191, 51))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.infa.setFont(font)
        self.infa.setStyleSheet("QPushButton { background-color: #f7943c;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.infa.setObjectName("infa")
        self.ema = QtWidgets.QPushButton(self.centralwidget)
        self.ema.setGeometry(QtCore.QRect(30, 500, 191, 51))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.ema.setFont(font)
        self.ema.setStyleSheet("QPushButton { background-color: #f7943c;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.ema.setObjectName("ema")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(320, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.save.setFont(font)
        self.save.setStyleSheet("QPushButton { background-color: #D6D607;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.save.setObjectName("save")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(230, 20, 161, 31))
        self.lineEdit.setStyleSheet("QLineEdit { border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;}")
        self.lineEdit.setObjectName("lineEdit")
        self.save_2 = QtWidgets.QPushButton(self.centralwidget)
        self.save_2.setGeometry(QtCore.QRect(220, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.save_2.setFont(font)
        self.save_2.setStyleSheet("QPushButton { background-color: #D6D607;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.save_2.setObjectName("save_2")
        self.paste = QtWidgets.QLineEdit(self.centralwidget)
        self.paste.setGeometry(QtCore.QRect(20, 150, 161, 31))
        self.paste.setStyleSheet("QLineEdit { border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;}")
        self.paste.setObjectName("paste")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 80, 281, 91))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.searchb = QtWidgets.QPushButton(self.centralwidget)
        self.searchb.setGeometry(QtCore.QRect(330, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.searchb.setFont(font)
        self.searchb.setStyleSheet("QPushButton { background-color: #20AA4C;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.searchb.setObjectName("searchb")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 160, 281, 91))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.paste_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.paste_2.setGeometry(QtCore.QRect(20, 220, 161, 31))
        self.paste_2.setStyleSheet("QLineEdit { border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501;}")
        self.paste_2.setObjectName("paste_2")
        self.save_3 = QtWidgets.QPushButton(self.centralwidget)
        self.save_3.setGeometry(QtCore.QRect(220, 220, 91, 31))
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        font.setBold(True)
        font.setWeight(75)
        self.save_3.setFont(font)
        self.save_3.setStyleSheet("QPushButton { background-color: #D6D607;  border-style: outset;\n"
"    border-width: 2.3px;\n"
"    border-radius: 10px;\n"
"    border-color: #050501; }")
        self.save_3.setObjectName("save_3")
        App.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(App)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        self.menuTinkoff_API = QtWidgets.QMenu(self.menubar)
        self.menuTinkoff_API.setStyleSheet("QMenu { background-color: #ffb337; border: none; }")
        self.menuTinkoff_API.setObjectName("menuTinkoff_API")
        App.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(App)
        self.statusbar.setObjectName("statusbar")
        App.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTinkoff_API.menuAction())

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "MainWindow"))
        self.label.setText(_translate("App", "Tinkoff API Trade Helper"))
        self.pokupka.setText(_translate("App", "Заявка на покупку"))
        self.label_2.setText(_translate("App", "Колличество лотов"))
        self.prodaja.setText(_translate("App", "Заявка на продажу"))
        self.label_3.setText(_translate("App", "Название бумаги"))
        self.vivod.setHtml(_translate("App", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'News701 BT\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p></body></html>"))
        self.infa.setText(_translate("App", "Информация об аккаунте"))
        self.ema.setText(_translate("App", "Построение графика EMA"))
        self.save.setText(_translate("App", "Сохранить"))
        self.save_2.setText(_translate("App", "Сохранить"))
        self.label_4.setText(_translate("App", "Название компании, поиск FIGI"))
        self.searchb.setText(_translate("App", "Поиск"))
        self.label_5.setText(_translate("App", "Задать FIGI для графика"))
        self.save_3.setText(_translate("App", "Сохранить"))
        self.menuTinkoff_API.setTitle(_translate("App", "Tinkoff API"))
